# Generated by Django 5.2 on 2025-04-17 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('director', models.CharField(max_length=100, verbose_name='감독')),
                ('genre', models.CharField(max_length=100, verbose_name='장르')),
                ('release_date', models.DateField(verbose_name='개봉일')),
                ('poster', models.URLField(blank=True, max_length=500, null=True, verbose_name='포스터')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='별점')),
                ('description', models.TextField(verbose_name='내용')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='작성자')),
                ('content', models.TextField(verbose_name='리뷰 내용')),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='평점')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='common.movie')),
            ],
        ),
    ]
