# Generated by Django 5.2 on 2025-04-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mypage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="movieCd",
            field=models.CharField(
                default="UNKNOWN", max_length=100, verbose_name="영화 코드"
            ),
        ),
        migrations.AlterModelTable(
            name="movie",
            table="mypage_movie",
        ),
    ]
