# Generated by Django 5.2 on 2025-04-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2, verbose_name='평점'),
        ),
    ]
